apiVersion: v1
kind: Service
metadata:
  name: scaletestapp
  labels:
    app: scaletestapp
spec:
  selector:
    app: scaletestapp
  ports:
    - name: http
      protocol: TCP
      port: 8080         # порт сервиса
      targetPort: 8080   # порт контейнера приложения
  type: ClusterIP
